site_name: QGIS Learning resources

theme:
  name: material
  palette:
    primary: green

plugins:
  - search
  - i18n:
      default_language: en
      languages:
        en: English
        it: Italano
